import type { CapabilityId } from "@/content/types";

export type ChunkType =
  | "bio"
  | "role"
  | "case_study"
  | "technology"
  | "discipline"
  | "capability"
  | "work_sample"
  | "numbers"
  | "method"
  | "targets";

/** Metadata attached to every chunk. Drives both retrieval boosts and the UI highlight payload. */
export interface ChunkMeta {
  company?: string;
  industry?: string;
  topic?: string;
  skills: string[];
  roleIds: string[];
  caseStudies: string[];
  technologies: string[];
  capabilities: CapabilityId[];
}

export interface Chunk {
  id: string;
  type: ChunkType;
  /** Human label shown in the Evidence / Sources list. */
  title: string;
  /** Where clicking the source takes the reader. */
  href: string;
  body: string;
  meta: ChunkMeta;
}

export interface ScoredChunk {
  chunk: Chunk;
  score: number;
}

/**
 * What the portfolio UI should highlight for a given question.
 * Derived from retrieved chunk metadata — never generated by the model.
 */
export interface FocusPayload {
  roleIds: string[];
  caseStudies: string[];
  technologies: string[];
  capabilities: CapabilityId[];
}

export interface Source {
  id: string;
  type: ChunkType;
  title: string;
  href: string;
  /** Short excerpt shown when the Evidence panel is expanded. */
  excerpt: string;
}
